### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by allentiak**
Revert "Move vcr-clj to dev profile"
This reverts commit bb08b0543878f6c276fb229ca94b20538bcfa8d5.

### CODE REVIEW

**Comment by nberger** [comment]
I suggest we keep it focused in fixing the build. I see there are commits that don't seem to be strictly related to fixing the build. Also, are you sure reverting that commit is the best way to fix the build. I'll take a look on that commit, I don't remember why I introduced it (I think it was during that short sprint where we were trying to upgrade deps and deploy to heroku, and we were trying different things until we realized there was some silly error) but also I'm not sure what went wrong with it.

**Comment by nberger** [comment]
So, the issue is the `n` missing in `depedencies`. Do you want to update this PR or send a new one to fix only that? I think we want to put it under the `dev` profile so it's not pulled as a transitive dependency in the projects that use this lib.

**Comment by allentiak** [comment]
I think the best will be to simply fix the commits in this branch. Just give me a few minutes...

**Comment by allentiak** [comment]
I think I fixed it. Could you please check it?

**Comment by nberger** [comment]
It's perfect now, thanks!

**Comment by allentiak** [comment]
You're welcome!

**Pull request merged**
